feat(ADP): Private cloud workflow. (#3926)
* feat: This large commit contains the separation of sytem type and project type notions. The commit covers all parts from the adp project except the deployment.

* feat: Add private cloud necessary changes to the deploy workflow.

* fix: When we re-run the generator with start-over button from th etemplate wizard we need to reset the data related to the system and project selection, otherwise it happens that the generator starts with an empty prompt for a system, which is ok, but the projectType prompt appears. This happens if in the previous generator run a mixed system was used(system which supports both cloud and onPrem projects)

* fix: The adp project type validation in deploy > destination prompt need to be executed only if the target system does NOT need authentication. This commit alsoreverts the fix in 2aeae85c3104f709ea9a3bc66ba8f531fa418ea8 and introduces a new correction - we hide the projectType prompt if there is no system selection yet, this is clean and easy to maintain than the previous fix.

* fix: There are onPrem systems for which the getSystemInfo call throws 404 or 405 error, for those systems we must return onPrem from the getSupportedProject method.

* fix: Remove redundant dependency to adp-tooling package + init adpProjectType directly in the deploy generetor constructor.

* fix: Change the way we pass the ADP project type from the ADP generator to the deploy generator, we mimic the backendTarget coupling.

* feat: Update the ADP cli - the add deploy command needs to set the adpProjectType.

* refactor: Some adpProjectType arguments of methods which do validation/visibility check could be avoided.

* refactor: Remove the error handlin ginside the getSystemInfo method. Add appropriate error handling related to the business logic when this helper method gets called.

* refactor: Remove redundant local variable + avoid local variable names with single letter.

* feat: When internal usage is enabled we need to set a default value for the projectType - onPremise. If the user selects cloudRedy project we need to display an error message beneath the projectType prompt.

* refactor: * Remove redundant target system prompt options.
* Remove the validateSystemType function because with the private cloud scenario it prevents the user from deploying cloud app created on a cloud system to a mixed system which supports both project types.
* PromptState.abapDeployConfig.isAbapCloud is overriden with the result from isAbapClooud() in case the shouldRestrictDifferentSystemType is true, which happens only in the adp workflow. This is also removed. The global flag is no more used in the adp workflow except in the when hook for the client prompt, there we can use the destination to determine the isAbapCloud flag value (isS4HC()).
* Refactor the function which determine th eproject type from the ui5.yaml to accept only the path to the root folder of the ADP project, the ui5.yaml config always resides on a root level so no need to explicitly pass the path to the yaml as a second argument.
* Add docs.
* When we validate the package type in the deploy wizard in case the system info api returns 404 we treat the package as a valid one.

* fix: Fix regression from d4bfffbd5e5717b1e96344f1b7cd2374470f36f7, forgot to pass the adpProjectType to the sub generator prompt options. The adpPojectType must also be passed to the sub generator options. The promptOptions.adpProjectType is used from the deploy-config generator and the options.adpProjectType is used from the abap-deploy-config sub generator.

* fix: When we validate the destination prompt in the deploy wizard in ADP workflow in case the api is not found we assume the system is onPremise. Add some docs and todos not related to the feature but for a future refactoring.

* fix: Fix an issue with the deploy wizard. In case we start the deploy generator as a standalone, we enter 2 systems which require credentials then the second system login always fails with 401 unauthorized(tested with u1y_010 then xid_080) nevertheless the credentials are correct. This is because the instance of the abap provider related to the second system is created without the credentials being passed before the login. The fix is to pass the credentials when the instance of the provider is created as a parameter to the AbapServiceProviderManager.getOrCreateServiceProvider() method. The issue is also observed in the legacy generator.

* feat: In the writing phase of the ADP generator we need to use the projectType instead of systemType when we assing the bspName and languages.

* fix: In the ADP generator writing phase we need to start using the project type instead of ato.operationsType.

* fix: When we validate the system in the ADP generator we re-throw any errors which does not match the current error handling by error status. Fix a misspelled property in the cloud app filter.

* fix: Correct lint issues.

* fix: Pass ADP project type to telemetry util not the system type.

* Linting auto fix commit

* fix: Correct import statements.

* test: Add unit tests.

* chore: Add cset.

* docs: Add docs in order to fix sonar issues.

* fix(legacy code blocker issues)(deploy): When we select a system in the deployment generator, when orchestrated by the ADP generator, we need to add a validation for the target system on which we deploy the ADP project. The validation uses the system info call to determine whether the ADP project type is supported by the target system. This change also fixes an issue in the abap provider manager. The manager creates for a system an object containing system url, destination etc. and the object creation is wrong because it can contain the url of the source system and the destination of the target system as it happens. The manager compares the source system object against the target system object, the object related to the target system is not correctly constructed, this results in a wrong assumption that the src system is equal to the target system, then we fetch the supported project types not for the target system but for the src. How to reproduce, select onPrem system for the ADP project and in the deploy page select cloud only system. Fix false positive tests, the validation of the system in the cli workflow does not work at all because the validateTargetSystem returns false instead of a string and the error in validateTargetSystemUrlCli is never thrown.

* feat: When we deploy cloud project on a private cloud system(system that supports both types of projects - onPrem and cloud) we need to pass the client in the ui5.yaml > builder > customTasks > configuration > target for custom task with name app-variant-bundler-build. This is mandatory otherwise the user will get errors on subsequent requests: Not authorized to create or update adaptation projects, status code 403.

* Revert "feat: When we deploy cloud project on a private cloud system(system that supports both types of projects - onPrem and cloud) we need to pass the client in the ui5.yaml > builder > customTasks > configuration > target for custom task with name app-variant-bundler-build. This is mandatory otherwise the user will get errors on subsequent requests: Not authorized to create or update adaptation projects, status code 403."

This reverts commit 15c2815694ad118438013536d110de70a0280c0c.

* fix: In adp-flp generator initialize the project type correctly - fix issue from the rebase. Fix failing unit test due to the changed amount of prompts in the adp generator.

* fix: When we create cloud project on a mixed system(system which supports cloud and onprem projects) we ust include in the builder task with name: app-variant-bundler-build in the target object the client.

* fix: Change strings.

* fix: When deploy config or backedn target is not yet provided the getSystemConfig will return system info object containing no props.

* chore: Update affected package versions with more precise version numbers reflecting the actual change complexity. Add docs.

* fix: Change strings.

* test: Fix failing test when update the branch with the latest changes from main. The failing discovery.test is hard to be root caused:

          TypeError: The original argument must be of type function. Received undefined

            1 | import type { Logger } from '@sap-ux/logger';
            2 | import type { AddressInfo } from 'node:net';
          > 3 | import open = require('open');
              | ^
            4 | import { defaultTimeout } from '../connection';
            5 | import { ABAPVirtualHostProvider } from './abap-virtual-host-provider';
            6 | import { setupRedirectHandling } from './redirect';

            at Object.<anonymous> (../../node_modules/.pnpm/open@7.0.3/node_modules/open/index.js:9:17)
            at Object.<anonymous> (../axios-extension/src/auth/reentrance-ticket/index.ts:3:1)
            at Object.<anonymous> (../axios-extension/src/auth/index.ts:4:1)
            at Object.<anonymous> (../axios-extension/src/base/service-provider.ts:6:1)
            at Object.<anonymous> (../axios-extension/src/index.ts:4:1)
            at Object.require (src/base/helper.ts:7:1)
            at Object.require (src/cf/project/yaml.ts:23:1)
            at Object.require (src/cf/project/index.ts:1:1)
            at Object.require (src/cf/services/api.ts:25:1)
            at Object.<anonymous> (test/unit/cf/app/discovery.test.ts:7:1)

the problem is from this line extracted from the stack trace:
at Object.require (src/base/helper.ts:7:1)

with the Private cloud workflow the helpers file starts to import the AdaptationProjectType const and use that const in the file, before that everything from the package was exported as type. In the test we have:

jest.mock('../../../../src/cf/services/api'') which mocks everything exported from the api file but does NOT ignore imports, that's how we reach the require('open') import and the corresponding error surfaced.

The fix is pretty simple we completely ignore everything from the module except the getFDCApps function.

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>