Enhancing writers to be more flexible for integration into `easyUI5` (#144)
* feat: make UI5 framwork configurable

* enhanced to support setting the UI5 framework to be used for local runs

* feat: added script to start with local UI5 sources

* fix: versioning, define empty string as latest

* fix: updated test snapshots with the new order of settings - no semantic change

* feat: add ui5 loading already in ui5-application

* update-snapshots: add ui5 loading already in ui5-application

* feat: allow merging of elements in yaml

* feat: refactor of ui5-config helper

* chore: better type usage

* feat: exposed required types

* feat: removed unnessary additions to the yamls

* updated lockfile

* chore: used more meaningful var name

* chore: fix file paths in launch.json

Also fix path to jest binary

```
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^
    SyntaxError: missing ) after argument list
```
This has started showing up on OS X as well
Fix from here: https://github.com/facebook/jest/issues/4751#issuecomment-361063215

* fix(yaml/ui5-config): add facility to getNode/Map/Seq in a Yaml doc

* fix: test snapshot update verified

* test: cleanup of test cases and improved coverage

* fix: added comments to public API

* doc: improved the readme

* chore: types cleanup

* feat: made view configurable

* fix: added backend to mui5-mock.yaml again because it is required for reuse libs

* fix: client regression

* fix: better import statement

* feat: allow optional properties for UI5 proxy

* fix: changed order of middlewares back to as before

* fix: switched order of middlewares back

* fix: forgot to update test snapshots

* fix: reverted renaming on vars

* fix: added handling for directLoad

* fix: test and snapshot cleanup

* fix: better separation of service and proxy settings

* lint: different things and stricter typing to reduce unnessary no-non-null-assertion

* fix: regression introduced with lint fixes

* lint: mostly jsdoc/

* lint: moved ignore comment into the prettified code

* refactor(ui5-app-writer): rm eslint-disable & reduce cognitive complexity

* changed const to enum to freeze its values

* feat: add inline schema for yaml-language-server in ui5*.yaml files

* chore: add changeset

* removed obsolete file

* changeset

* enhanced test case

Co-authored-by: Ullas Holla <ullas.holla@sap.com>