chore: fix file paths in launch.json
Also fix path to jest binary

```
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^
    SyntaxError: missing ) after argument list
```
This has started showing up on OS X as well
Fix from here: https://github.com/facebook/jest/issues/4751#issuecomment-361063215