test: Fix failing test when update the branch with the latest changes from main. The failing discovery.test is hard to be root caused:
          TypeError: The original argument must be of type function. Received undefined

            1 | import type { Logger } from '@sap-ux/logger';
            2 | import type { AddressInfo } from 'node:net';
          > 3 | import open = require('open');
              | ^
            4 | import { defaultTimeout } from '../connection';
            5 | import { ABAPVirtualHostProvider } from './abap-virtual-host-provider';
            6 | import { setupRedirectHandling } from './redirect';

            at Object.<anonymous> (../../node_modules/.pnpm/open@7.0.3/node_modules/open/index.js:9:17)
            at Object.<anonymous> (../axios-extension/src/auth/reentrance-ticket/index.ts:3:1)
            at Object.<anonymous> (../axios-extension/src/auth/index.ts:4:1)
            at Object.<anonymous> (../axios-extension/src/base/service-provider.ts:6:1)
            at Object.<anonymous> (../axios-extension/src/index.ts:4:1)
            at Object.require (src/base/helper.ts:7:1)
            at Object.require (src/cf/project/yaml.ts:23:1)
            at Object.require (src/cf/project/index.ts:1:1)
            at Object.require (src/cf/services/api.ts:25:1)
            at Object.<anonymous> (test/unit/cf/app/discovery.test.ts:7:1)

the problem is from this line extracted from the stack trace:
at Object.require (src/base/helper.ts:7:1)

with the Private cloud workflow the helpers file starts to import the AdaptationProjectType const and use that const in the file, before that everything from the package was exported as type. In the test we have:

jest.mock('../../../../src/cf/services/api'') which mocks everything exported from the api file but does NOT ignore imports, that's how we reach the require('open') import and the corresponding error surfaced.

The fix is pretty simple we completely ignore everything from the module except the getFDCApps function.